import fs from 'node:fs';
import path from 'node:path';

import { defineConfig } from 'vite';
import { svelte } from '@sveltejs/vite-plugin-svelte';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
https://github.com/kalinichenko88/obsidian-budget-planner-plugin
*/
`;

// Copy static files function
const copyFiles = () => {
  const files = ['manifest.json'];
  const outDir = 'dist';

  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  files.forEach((file) => {
    fs.copyFileSync(path.resolve(file), path.resolve(outDir, file));
  });
};

// Copy files only via the Vite plugin hook

const alias = {
  '@': path.resolve(__dirname, 'src'),
};

// Keyed off Vite's own mode, never an ambient process.env.NODE_ENV. Vite derives
// isProduction — and with it the Svelte compiler's dev flag — from NODE_ENV when
// one is already set, so a build environment that presets it would silently ship
// an unminified, inline-sourcemapped artifact. Pinning it here keeps `vite build`
// byte-reproducible however it is invoked. Vitest (mode 'test') is left alone.
export default defineConfig(({ mode }) => {
  const isDev = mode !== 'production';
  if (!isDev) {
    process.env.NODE_ENV = 'production';
  }

  return {
    resolve: process.env.VITEST
      ? {
          conditions: ['browser'],
          alias,
        }
      : {
          alias,
        },
    plugins: [
      svelte({
        compilerOptions: { css: 'injected' },
      }),
      {
        name: 'copy-files',
        apply: 'build',
        writeBundle() {
          copyFiles();
        },
      },
      {
        name: 'add-banner',
        generateBundle(_, bundle) {
          for (const fileName in bundle) {
            if (fileName === 'main.js') {
              const asset = bundle[fileName];
              if (asset.type === 'chunk') {
                asset.code = banner + asset.code;
              }
            }
          }
        },
      },
    ],
    build: {
      lib: {
        entry: path.resolve(__dirname, 'src/main.ts'),
        formats: ['cjs'],
        fileName: () => 'main.js',
      },
      rollupOptions: {
        external: [
          'obsidian',
          'electron',
          '@codemirror/autocomplete',
          '@codemirror/collab',
          '@codemirror/commands',
          '@codemirror/language',
          '@codemirror/lint',
          '@codemirror/search',
          '@codemirror/state',
          '@codemirror/view',
          '@lezer/common',
          '@lezer/highlight',
          '@lezer/lr',
        ],
        output: {
          entryFileNames: 'main.js',
          dir: 'dist',
          format: 'cjs',
        },
      },
      sourcemap: isDev ? 'inline' : false,
      minify: !isDev,
      emptyOutDir: false, // Don't clean the output directory before building
      outDir: 'dist',
    },
  };
});
